/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://7h2kbv76yfhbli2zylquuacfgq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jqncun3ghnd7nmyovkjotkcx6y",
    "aws_cloud_logic_custom": [
        {
            "name": "events",
            "endpoint": "https://fkr45a9es4.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "test",
            "endpoint": "https://2ywqr95ucf.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "borderevent",
            "endpoint": "https://qbyirtndb7.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "tasks",
            "endpoint": "https://9541p8ug11.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:bd92abcf-ba67-4f52-8f90-9540838504d9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xd6I6B50w",
    "aws_user_pools_web_client_id": "6f3ut1ngg73e69nhal95gpvamd",
    "oauth": {}
};


export default awsmobile;
